### ISSUE TITLE
Bug: beta et code

### ISSUE THREAD

**Issue by UnTanukii** [Brize-Glace/ILLENIUMUWUWUWUWUWUWUWU#4]
**Describe the bug**
Nous pouvons activer le bêta mode en appuyant sur toutes les touches. Il faudra, selon moi, vérifier que les touches appuyés sont uniquement B E T et A et qu'elles sont tapés dans le bon ordre.

**Desktop (please complete the following information):**
 - OS: Windows (mais ça marche partout)
 - Browser : Brave (mais ça marche sur tout)
 
**Additional content**
Par ailleurs, en regardant dans le network de l'inspect du web site de l'Internet nous pouvons analyser la réponse de l'API et récupérer tous les codes BETA (ATTENTION FAILLE DE SECURITE GRAVE, PAS BIEN)

Cordialement, le bug hunter Discord, bêta testeur et développeur d'Elixir, développeur du projet Astrion, projet Astrion beta et projet Astrion développement, développeur de Orna's Games, de Orna's Mod, de Orna, développeur FiveM, développeur d'un jeu pas encore sorti mais bientôt, ahah, c'est juste un leak, développeur de texte (Les Misérables, La Malade Imaginaire, j'ai développé 2/3 lignes en plus histoire de...), développeur couché, développeur debout, et surtout, développeur de passions et de rêves. J'aime explorer de nouvelles technologies, créer des expériences numériques, et participer à des projets variés. Mon parcours est marqué par la curiosité et le désir constant d'apprendre, d'innover et de partager. Le développement n'est pas seulement un métier, c'est une véritable passion, et je suis ravi de contribuer à tant de projets différents et passionnants. (désolé j'ai trop développer: problème de <b>développeur</b>) Par ailleurs une petite aide financière pour la recherche de ce bug qui est une FAILLE DE SECURITE IMPORTANTE serait accepté pour mes enfants, mon labrador qui s'appelle Naps (comme le rappeur), ma clio 4 en fin de vie avec des autocollants zero two offert par mon très cher ami StevenTed qui habite proche d'Avignon (Avignon est une charmante ville située dans le sud de la France, nichée dans la région Provence-Alpes-Côte d'Azur. Elle est renommée pour son riche patrimoine historique, sa culture vibrante et son atmosphère méridionale ensoleillée.)
Bisous à bientôt ;)

**Comment by Brize-Glace** [comment]
Bonjour,
Merci pour votre rapport. Un patch est en cours de developpement pour le problème soulevé. Hors, pour l'histoire de la faille de sécurité, c'est une faille qui a été generer exprès pour que les utilisateur aient accès aux codes betacar ceux ci ne sont pas donnés a des gens spécifiques.

**Comment by Brize-Glace** [comment]
Bonjour @UnTanukii ,

Le bug a normalement été patché. 
Merci pour votre rapport!

**Comment by Brize-Glace** [comment]
FINI
